<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Predis\\' => array($vendorDir . '/predis/predis/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'MongoDB\\' => array($vendorDir . '/mongodb/mongodb/src'),
    'Junnu\\Guvi\\' => array($baseDir . '/src'),
    'Jean85\\' => array($vendorDir . '/jean85/pretty-package-versions/src'),
);
